/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./components/ui/button/Button.vue')['default']
    Dialog: typeof import('./components/ui/dialog/Dialog.vue')['default']
    DialogClose: typeof import('./components/ui/dialog/DialogClose.vue')['default']
    DialogContent: typeof import('./components/ui/dialog/DialogContent.vue')['default']
    DialogDescription: typeof import('./components/ui/dialog/DialogDescription.vue')['default']
    DialogFooter: typeof import('./components/ui/dialog/DialogFooter.vue')['default']
    DialogHeader: typeof import('./components/ui/dialog/DialogHeader.vue')['default']
    DialogScrollContent: typeof import('./components/ui/dialog/DialogScrollContent.vue')['default']
    DialogTitle: typeof import('./components/ui/dialog/DialogTitle.vue')['default']
    DialogTrigger: typeof import('./components/ui/dialog/DialogTrigger.vue')['default']
    Input: typeof import('./components/ui/input/Input.vue')['default']
    Label: typeof import('./components/ui/label/Label.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./components/ui/select/Select.vue')['default']
    SelectContent: typeof import('./components/ui/select/SelectContent.vue')['default']
    SelectGroup: typeof import('./components/ui/select/SelectGroup.vue')['default']
    SelectItem: typeof import('./components/ui/select/SelectItem.vue')['default']
    SelectItemText: typeof import('./components/ui/select/SelectItemText.vue')['default']
    SelectLabel: typeof import('./components/ui/select/SelectLabel.vue')['default']
    SelectScrollDownButton: typeof import('./components/ui/select/SelectScrollDownButton.vue')['default']
    SelectScrollUpButton: typeof import('./components/ui/select/SelectScrollUpButton.vue')['default']
    SelectSeparator: typeof import('./components/ui/select/SelectSeparator.vue')['default']
    SelectTrigger: typeof import('./components/ui/select/SelectTrigger.vue')['default']
    SelectValue: typeof import('./components/ui/select/SelectValue.vue')['default']
  }
}
